#!/usr/bin/env python3
"""Scrape the Wetland Plants special-offers page into _data/offers.yml.

Runs in GitHub Actions on a schedule. It targets the standard WooCommerce
product-loop markup, so it is resilient to content changes but will need the
selectors updated if the shop ever re-themes.

On any failure it preserves the previously-scraped products and records an
error string, so the site always builds with the last known-good list.
"""

import datetime as dt
import re
import sys
from pathlib import Path

import requests
import yaml
from bs4 import BeautifulSoup

# --- Parameters --------------------------------------------------------------
SOURCE_URL = "https://wetland-plants.co.uk/product-category/special-offers/?orderby=price"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "_data" / "offers.yml"
REQUEST_TIMEOUT = 20  # seconds
USER_AGENT = "peasoup-pond-bot/1.0 (personal pond project; contact nthndy@gmail.com)"
MAX_PRODUCTS = 24  # safety cap
# -----------------------------------------------------------------------------


def money_to_float(text):
    """Turn a price string like '£1,234.00' into 1234.0, or None if unparseable."""
    match = re.search(r"[\d,]+\.?\d*", text.replace(",", ""))
    return float(match.group()) if match else None


def first_amount(node):
    """Return the trimmed text of the first WooCommerce price amount in `node`."""
    if node is None:
        return ""
    amount = node.select_one(".woocommerce-Price-amount")
    target = amount or node
    return target.get_text(strip=True)


def parse_price(product):
    """Extract (current_display, was_display, current_value) from a product."""
    price = product.select_one(".price")
    if price is None:
        return "", "", None

    sale = price.select_one("ins")
    original = price.select_one("del")

    if sale is not None:
        current = first_amount(sale)
        was = first_amount(original)
    else:
        current = first_amount(price)
        was = ""

    return current, was, money_to_float(current)


def parse_image(product):
    """Return a usable image URL, preferring a real src over a lazy placeholder."""
    img = product.select_one("img")
    if img is None:
        return ""
    for attr in ("src", "data-src", "data-lazy-src"):
        value = img.get(attr, "")
        if value and "svg+xml" not in value:
            return value
    srcset = img.get("srcset", "")
    return srcset.split(" ")[0] if srcset else ""


def scrape():
    """Fetch and parse the offers page into a list of product dicts."""
    response = requests.get(
        SOURCE_URL,
        headers={"User-Agent": USER_AGENT},
        timeout=REQUEST_TIMEOUT,
    )
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")

    products = []
    for product in soup.select("li.product")[:MAX_PRODUCTS]:
        title_el = product.select_one(".woocommerce-loop-product__title")
        link_el = product.select_one("a.woocommerce-LoopProduct-link") or product.find("a", href=True)
        if title_el is None or link_el is None:
            continue

        current, was, value = parse_price(product)
        products.append(
            {
                "name": title_el.get_text(strip=True),
                "url": link_el["href"],
                "image": parse_image(product),
                "price": current,
                "was": was,
                "price_value": value,
                "on_sale": bool(was),
            }
        )
    return products


def load_existing():
    """Return the current offers.yml contents, or a blank scaffold."""
    if OUTPUT_PATH.exists():
        with OUTPUT_PATH.open(encoding="utf-8") as handle:
            return yaml.safe_load(handle) or {}
    return {}


def write(data):
    header = (
        "# AUTO-GENERATED by .github/workflows/scrape-offers.yml\n"
        "# Do not edit by hand.\n"
    )
    with OUTPUT_PATH.open("w", encoding="utf-8") as handle:
        handle.write(header)
        yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False)


def main():
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    try:
        products = scrape()
        write(
            {
                "updated": now,
                "source": SOURCE_URL,
                "error": "",
                "products": products,
            }
        )
        print(f"Wrote {len(products)} offers to {OUTPUT_PATH}")
    except Exception as exc:  # noqa: BLE001 - keep the site building on any failure
        existing = load_existing()
        write(
            {
                "updated": existing.get("updated", ""),
                "source": SOURCE_URL,
                "error": f"{type(exc).__name__}: {exc}",
                "products": existing.get("products", []),
            }
        )
        print(f"Scrape failed, preserved existing list: {exc}", file=sys.stderr)
        # Exit 0 so the workflow still commits and Pages rebuilds cleanly.


if __name__ == "__main__":
    main()
